version: "3"
services:
  postgres:
    image: postgres:10.7-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: stryp
      POSTGRES_PASSWORD: MySecretPassword
    volumes:
       - db-data:/var/lib/postgresql/data

volumes:
  db-data: